server:
  type: default
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors:
    - type: http
      port: 8082

database:
  driverClass: org.postgresql.Driver
  user: pipuser
  password: pippass
  url: jdbc:postgresql://postgres:5432/pipdb
  properties:
    charSet: UTF-8